// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entity/favorite_movie_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 799578204794185986),
      name: 'FavoriteMovieEntity',
      lastPropertyId: const IdUid(4, 3902188267315212236),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7031349325881901619),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 3893244265795129830),
            name: 'movieId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3902188267315212236),
            name: 'movieJsonStr',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 799578204794185986),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [2560052406857957526],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    FavoriteMovieEntity: EntityDefinition<FavoriteMovieEntity>(
        model: _entities[0],
        toOneRelations: (FavoriteMovieEntity object) => [],
        toManyRelations: (FavoriteMovieEntity object) => {},
        getId: (FavoriteMovieEntity object) => object.id,
        setId: (FavoriteMovieEntity object, int id) {
          object.id = id;
        },
        objectToFB: (FavoriteMovieEntity object, fb.Builder fbb) {
          final movieJsonStrOffset = object.movieJsonStr == null
              ? null
              : fbb.writeString(object.movieJsonStr!);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.movieId);
          fbb.addOffset(3, movieJsonStrOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final movieIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final movieJsonStrParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final object = FavoriteMovieEntity(
              id: idParam,
              movieId: movieIdParam,
              movieJsonStr: movieJsonStrParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [FavoriteMovieEntity] entity fields to define ObjectBox queries.
class FavoriteMovieEntity_ {
  /// see [FavoriteMovieEntity.id]
  static final id =
      QueryIntegerProperty<FavoriteMovieEntity>(_entities[0].properties[0]);

  /// see [FavoriteMovieEntity.movieId]
  static final movieId =
      QueryIntegerProperty<FavoriteMovieEntity>(_entities[0].properties[1]);

  /// see [FavoriteMovieEntity.movieJsonStr]
  static final movieJsonStr =
      QueryStringProperty<FavoriteMovieEntity>(_entities[0].properties[2]);
}
